# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import time

import os
import matplotlib.pyplot as plt
import matplotlib.animation as animation

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure

import matplotlib.pyplot as plt


from PyQt5.Qt import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

import UI

class ExampleApp(QtWidgets.QMainWindow,UI.Ui_MainWindow):

    def __init__(self):
        super().__init__()
        self.setupUi(self)
        
        self.but_click = True
        self.canavas = MyMplCanvas()

        self.pushButton_4.clicked.connect(self.click)
        self.pushButton_5.clicked.connect(self.Click_Update)
        self.pushButton_2.clicked.connect(self.color)
        self.pushButton.clicked.connect(self.color2)
        self.pushButton_3.clicked.connect(self.color3)

        self.mythread = MyThread(self.on_change())
        self.mythread.mysignal.connect(self.on_change, QtCore.Qt.QueuedConnection)

    def color(self):
      
            self.pushButton_2.setStyleSheet("""
    QPushButton:hover { background-color: rgb(137, 228, 255); }
    QPushButton:!hover { background-color: rgb(137, 228, 255); }
    
""")
            self.pushButton.setStyleSheet("""
    QPushButton:hover { background-color: rgb(248, 48, 255); }
    QPushButton:!hover { background-color:  rgb(244, 44, 255) }
    
""") 

            self.pushButton_3.setStyleSheet("""
    QPushButton:hover { background-color: rgb(248, 48, 255); }
    QPushButton:!hover { background-color:  rgb(244, 44, 255) }
    
""") 

    def color2(self):
            
            
            self.pushButton.setStyleSheet("""
    QPushButton:hover { background-color: rgb(137, 228, 255); }
    QPushButton:!hover { background-color: rgb(137, 228, 255); }
    
""")
            self.pushButton_2.setStyleSheet("""
    QPushButton:hover { background-color: rgb(248, 48, 255); }
    QPushButton:!hover { background-color:  rgb(244, 44, 255) }
    
""") 

            self.pushButton_3.setStyleSheet("""
    QPushButton:hover { background-color: rgb(248, 48, 255); }
    QPushButton:!hover { background-color:  rgb(244, 44, 255) }
    
""") 


    def color3(self):
            
            self.pushButton_3.setStyleSheet("""
    QPushButton:hover { background-color: rgb(137, 228, 255); }
    QPushButton:!hover { background-color: rgb(137, 228, 255); }
    
""")
            self.pushButton_2.setStyleSheet("""
    QPushButton:hover { background-color: rgb(248, 48, 255); }
    QPushButton:!hover { background-color:  rgb(244, 44, 255) }
    
""") 

            self.pushButton.setStyleSheet("""
    QPushButton:hover { background-color: rgb(248, 48, 255); }
    QPushButton:!hover { background-color:  rgb(244, 44, 255) }
    
""") 
    def on_change(self,s=0,time=0):
        _translate = QtCore.QCoreApplication.translate
        self.label_4.setText(_translate("MainWindow", str(float('{:.2f}'.format(s)))))
        return time

        
    def click(self):
        if self.but_click==True:
         self.pushButton_4.setIcon(self.icon2)
         self.but_click =False
         
         self.layout = QVBoxLayout(self.frame_8)
         self.layout.addWidget(self.canavas) 

         self.mythread.start()
         self.canavas.start()   
         self.mythread.arr =True
         
        else:
            self.pushButton_4.setIcon(self.icon)
            self.but_click = True
            self.mythread.arr =False
           
    def Click_Update(self):
        os.remove("C:\\Python\\Text.txt")
        open("C:\\Python\\Text.txt", "a+")

# getting the temperature value from the sensor in a separate stream
class MyThread(QtCore.QThread):
    mysignal = QtCore.pyqtSignal(float,int)
    def __init__(self,timesi=0, parent=None):
        QtCore.QThread.__init__(self, parent)
        self.arr = False
        self.times = 0
        self.res = 0
        self.timesi = timesi
    def run(self):
        import serial
        ser = serial.Serial('COM3', 9600)
        
        while self.arr:
            ser
            data = ser.readline()
            self.res = float(data[0:5])
            time.sleep(1)
            self.timesi+=1
            val = ",".join([str(self.res),str(self.timesi)]) 
            with open('C:\\Python\\Text.txt','a+',encoding='utf-8') as fp:
                fp.write(val+"\n")

            self.mysignal.emit(self.res,self.timesi)
        


# updates the graph by reading the temperature values from the Text file.
class MyMplCanvas(FigureCanvas):

    def __init__(self,  *args, **kwargs):
        self.fig = Figure()
        super(MyMplCanvas, self).__init__(self.fig, *args, **kwargs)
        self.ax1 = self.fig.add_subplot(1, 1, 1)

    def start(self):
        self.ax1.set(facecolor = "mediumslateblue")
        self.fig.set(facecolor = "purple")
        self.fig.patch.set_alpha(0.002)
        self.ax1.set_alpha(0.002)
        self.ax1.set_xticks([],   minor=False)
        self.ax1.set_yticks([],   minor=False)
        self.ax1.spines['top'].set_visible(False)
        self.ax1.spines['right'].set_visible(False)
        self.ax1.spines['bottom'].set_visible(False)
        self.ax1.spines['left'].set_visible(False)        
        self.ani = animation.FuncAnimation(self.fig, self.animate, interval=1000) 
        plt.show()

    def file(self):  
        data = open('C:\\Python\\Text.txt', 'r',encoding='utf-8').read()
        lines = data.split('\n')
        xs = []
        ys = []
        
        for line in lines:
            if line != "":
                y, x = line.split(',')  # Separating the date from the price
                xs.append(x)
                ys.append(float(y))
               
        return xs,ys

    def animate(self,i=0): 
        large = 22; med = 10; small = 12
        params = {'axes.titlesize': large,
                'legend.fontsize': med,
                'figure.figsize': (25, 15),
                'axes.labelsize': med,
                'axes.titlesize': med,
                'xtick.labelsize': med,
                'ytick.labelsize': med,
                'figure.titlesize': large}

        plt.rcParams.update(params)
        
        xs,ys = self.file()
        self.ax1.clear()
        self.ax1.fill_between(xs, y1=ys, y2=0, alpha=0.4, color ='tab:red', linewidth=2)
        self.ax1.set_xticks([],   minor=False)
        if os.stat('C:\\Python\\Text.txt').st_size != 0:
            pos = 0
            self.ax1.set(xlim = [pos,xs[-1]])
            self.ax1.set(ylim=[max(ys)-2, max(ys)+2])
 
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = ExampleApp()
    ui.show()
    sys.exit(app.exec_())
       
